### ISSUE TITLE
Does not work with gatsby-transformer-sharp

### ISSUE THREAD

**Issue by chriserickson** [neugelb/gatsby-plugin-generate-typings#2]
Hey, thanks for making this plugin!

I'm trying to use it with gatsby-images and gatsby-transformer-sharp, but it can't generate the types when using their fragment. I'm not sure whether it is possible to get the schema generated after the transformers are applied or not. 

Example:
CMS / MD
```
templateKey: index-page
title: Some page

links:
  - label: Some other page
    url: /whatever
    image: /img/my-image.png
```

Query:
```
export const pageQuery = graphql`
  query IndexPageTemplate {
    markdownRemark(frontmatter: { templateKey: { eq: "index-page" } }) {
      frontmatter {
        title
        links {
          label
          url
          image {
            childImageSharp {
              fluid(maxWidth: 240, quality: 64) {
                ...GatsbyImageSharpFluid
              }
            }
          }
        }
      }
    }
  }
`;
```

Error:
```
Field "image" must not have a selection since type "String" has no subfields
```
